spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myShop?characterEncoding=UTF-8
    username: root
    password: Cqmygysdss
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create